services:
  - type: web
    name: rezopaint
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
